# Site settings
title: ShapeMI MICCAI 2018
email: shapemi2018@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Workshop on Shape in Medical Imaging
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#github_username:shapemi

# Build settings
markdown: kramdown
